### PR TITLE
Connected endpoints and updated ui

### PR DESCRIPTION
**Pull request by gambhir-harshil**
- Connected login and register endpoints
- Added necessary changes to the UI
- fixed some routing issues
- added images

### CODE REVIEW

**Review by civilgoody — COMMENTED** [review]
I highly recommend following the guidance provided in the article on implementing the frontend authentication flow: [User Registration and Login in Next.js 13](https://codevoweb.com/user-registration-login-in-nextjs-13-app-directory/). Here's why I believe it's a valuable resource for our project:

1. **Experienced Author:** The article is written by an experienced author who demonstrates a deep understanding of best practices in Next.js development. They make extensive use of reusable code, which aligns with industry standards.

2. **Client-side Validation:** One notable advantage of this approach is the user-friendly client-side validation. It minimizes the need for unnecessary server-side requests for validation, enhancing the overall user experience. Please refer to this [sample image](https://github.com/gambhir-harshil/leetcode-api/assets/108733847/90db2118-b5fa-4d61-8c4a-73a92b1f0df5) from the article to see this in action.

### Additional Notes:

- The article suggests using `Zustland` for global state management. While we can explore alternatives if you have a preference, `Zustland` appears to be a straightforward and efficient choice for our needs.

I genuinely believe that implementing the practices outlined in this article will contribute significantly to the quality of our app. Even as we continue to make improvements, following these guidelines will help us maintain a strong foundation.

I'm also more than willing to collaborate with you on this, should you need any assistance or have questions. Let's strive for excellence together! :pray:

I also followed a similar [article](https://codevoweb.com/jwt-authentication-in-nextjs-13-api-route-handlers/) by the same author for the backend, as I trust in adhering to best practices.

**Comment by ninjamovesonly** [comment]
I don't mind react context api for global state management and usestate hook for regular state management but I will take a good look at Zustand and this pull request

Is it possible to squash commits to just one so I can easily take a good look @gambhir-harshil 

Also take off the console statements else everything looks good 🙂

@cfoulk what do you think?

**Comment by cfoulk** [comment]
> I don't mind react context api for global state management and usestate hook for regular state management but I will take a good look at Zustand and this pull request
> 
> Is it possible to squash commits to just one so I can easily take a good look @gambhir-harshil
> 
> Also take off the console statements else everything looks good 🙂
> 
> @cfoulk what do you think?

I am ok with react context aswell. For the commits you could rebase essentially making them into one or two commits instead of the long list of commits.

**Review by cfoulk — APPROVED** [review]
Much of the new functionality is working on my machine. New registrations are showing up in my local DB.

**Review by cfoulk — APPROVED** [review]

**Pull request merged**
